### ISSUE TITLE
max_clade issue

### ISSUE THREAD

**Issue by muniheart** [niemasd/TreeCluster#4]
I notice that function min_clusters_threshold_max_clade calls treeswift.resolve_polytomies.  Given the tree,
(A:2,B:2,C:1);
TreeCluster.py -t 3 -i <( echo "(A:2,B:2,C:1)" )
SequenceName ClusterNumber
A -1
B 1
C 1
This breaks the clade (A,B,C) into 2 clusters.  On the other hand, if you comment out line 415, the result is,
SequenceName ClusterNumber
A -1
B -1
C -1
of which each cluster is a clade.

**Comment by niemasd** [comment]
Thanks for catching this! I had implemented this one using the non-clade version as a starting point (I believe the polytomy resolution works fine there), but it doesn't work here :-) I'll push a fix shortly

**Comment by niemasd** [comment]
I just pushed a fix and created a new release with it (1.0.3). The fix was a little more involved than just not suppressing polytomies, as it would then potentially break in when all individual pairwise leaf distances are below the threshold but the sum of leaf distances is greater than the threshold, e.g. the following:

```bash
TreeCluster.py -t 5 -i <( echo "(A:2,B:2,C:2)" )
```

It would also break the other clustering approaches that depend on a bifurcating tree (e.g. the non-``clade`` approaches). Instead, I just keep track of the two largest pairwise distances to determine the maximum pairwise distance below a given node

I need to investigate the other ``_clade`` methods to make sure this bug didn't affect them as well, so I'll keep this Issue open for now, but ``max_clade`` specifically should be fixed :-) Thanks again!

**Comment by dfornika** [comment]
Hi @niemasd, could you push the v1.0.3 release that you mentioned above to [pypi](https://pypi.org/project/treecluster/) when you have a chance?

**Comment by niemasd** [comment]
Ah, sincerest apologies; it slipped my mind. I have just pushed the 1.0.3 release to pypi
